mkdir -p public/.well-known
cat > public/.well-known/xrp-ledger.toml <<'TOML'
# XRPL Token TOML for $BAG
# Last updated: 2025-08-09

[METADATA]
website = "https://getthebag.io"
x = "https://x.com/getthebag_io"
description = "Utility on Chain. Culture on Brand. XRPL's heaviest meme - Official $BAG Token. 1T supply. Built to flex. Powered by $XRP."

# --- Currency ---
[[CURRENCIES]]
code = "BAG"
issuer = "rNeYbfb9EDV8c7mNfUuooEEYYzMcEuDFbr"
network = "mainnet"
name = "$BAG"
desc = "Utility on Chain. Culture on Brand. XRPL's heaviest meme - Official $BAG Token. 1T supply. Built to flex. Powered by $XRP."
icon = "https://getthebag.io/logo.png"
display_decimals = 6

# --- Accounts ---
[[ACCOUNTS]]
address = "rNeYbfb9EDV8c7mNfUuooEEYYzMcEuDFbr"
network = "mainnet"
role = "issuer"
desc = "Official $BAG token issuer (mint address)"

[[ACCOUNTS]]
address = "raoC1r3rTXzG5qppic6VYCqqY87fFcUJch"
network = "mainnet"
role = "treasury"
desc = "Treasury wallet. OTC sales, project operations."

[[ACCOUNTS]]
address = "rQBXxZ7PwTHF3oFDQ8qhZtizvv2kiMcw17"
network = "mainnet"
role = "liquidity"
desc = "Liquidity wallet. DEX/pool funding."

[[ACCOUNTS]]
address = "rJZQH85kH4mMiASm7BxdmjorBonvLeDfrR"
network = "mainnet"
role = "reserve"
desc = "Principal wallet."

[DISCLAIMER]
text = "This is an independent meme token project. $BAG is not affiliated with Ripple or any other entity. Always verify the issuer address. All tokens are distributed and managed transparently on the XRPL."
TOML

git add public/.well-known/xrp-ledger.toml
git commit -m "Write clean UTF-8 safe TOML for $BAG"
git push
