# XRPL Token TOML for $BAG
# Last updated: 2025-08-06

[METADATA]
modified = "2025-08-06"
version = "1.0"

[[CURRENCIES]]
code = "BAG"
issuer = "rNeYbfb9EDV8c7mNfUuooEEYYzMcEuDFbr"
name = "$BAG"
desc = "Utility on Chain. Culture on Brand. XRPL’s heaviest meme — Official $BAG Token. 1T supply. Built to flex. Powered by $XRP."
icon = "https://getthebag.io/logo.png"
url = "https://getthebag.io"
decimals = 6

[[ACCOUNTS]]
address = "rNeYbfb9EDV8c7mNfUuooEEYYzMcEuDFbr"
role = "issuer"
desc = "Official $BAG token issuer (mint address)"

[[ACCOUNTS]]
address = "raoC1r3rTXzG5qppic6VYCqqY87fFcUJch"
role = "treasury"
desc = "Treasury wallet. OTC sales, project operations."

[[ACCOUNTS]]
address = "rQBXxZ7PwTHF3oFDQ8qhZtizvv2kiMcw17"
role = "liquidity"
desc = "Liquidity wallet. DEX/pool funding."

[[ACCOUNTS]]
address = "rJZQH85kH4mMiASm7BxdmjorBonvLeDfrR"
role = "reserve"
desc = "Principal wallet."

[INFO]
website = "https://getthebag.io"
twitter = "https://x.com/getthebag_io"
whitepaper = ""
discord = ""
telegram = ""

[VALIDATORS]
# Leave blank unless you run a validator

[PRINCIPALS]
# Add team or founder contacts if desired

[DISCLAIMER]
text = "This is an independent meme token project. $BAG is not affiliated with Ripple or any other entity. Always verify the issuer address. All tokens are distributed and managed transparently on the XRPL."
