# XRPL Token TOML for $BAG
# Last updated: 2025-08-10

[[CURRENCIES]]
code   = "BAG"
currency_hex = "4241470000000000000000000000000000000000"
issuer = "rNeYbfb9EDV8c7mNfUuooEEYYzMcEuDFbr"
network = "main"
name    = "BAG"
desc    = "Utility on Chain. Culture on Brand. XRPL's Heaviest Meme. Official $BAG token. Total supply 1,000,000,000,000."
icon    = "https://getthebag.io/logo.png"
display_decimals = 6

[[CURRENCIES.urls]]
type  = "website"
title = "Official Website"
url   = "https://getthebag.io"

[[CURRENCIES.urls]]
type  = "social"
title = "X Social"
url   = "https://x.com/getthebag_io"

# Last updated: 2025-08-10

[[CURRENCIES.urls]]
type  = "social"
title = "Telegram"
url   = "https://t.me/getthebag_io"

[[ACCOUNTS]]
address = "rNeYbfb9EDV8c7mNfUuooEEYYzMcEuDFbr"
network = "main"
role    = "issuer"
desc    = "Official $BAG token issuer"
domain  = "getthebag.io"

[[ACCOUNTS]]
address = "raoC1r3rTXzG5qppic6VYCqqY87fFcUJch"
network = "main"
role    = "treasury"
desc    = "Treasury / OTC"

[[ACCOUNTS]]
address = "rQBXxZ7PwTHF3oFDQ8qhZtizvv2kiMcw17"
network = "main"
role    = "liquidity"
desc    = "DEX / pools"

[[ACCOUNTS]]
address = "rJZQH85kH4mMiASm7BxdmjorBonvLeDfrR"
network = "main"
role    = "reserve"
desc    = "Principal wallet"
# redeploy to refresh logo


